### ISSUE TITLE
Opening logo cinematics and demos don't play on start

### ISSUE THREAD

**Issue by NeonKnightOA** [yquake2/rogue#12]
Using Yamagi Quake II ver. 7.30 and Rogue ver. 2.04 under Windows 7.

Opening the game through a shortcut (with +game rogue) has the game go directly to the console. It doesn't play the opening logos or the demos.

**Comment by Yamagi** [comment]
I can't reproduce this. Is this still the case in the latest version? If yes, do you have unicode chars in the games path or in your Windows user name?
