### ISSUE TITLE
Relicense Yamagi Quake II Rogue (Ground Zero) under GPL2

### ISSUE THREAD

**Issue by Yamagi** [yquake2/rogue#122]
Hi,

until now the Quake II addons were licensed under the id Software SDK license, which isn't really an open source license. It causes problems with distributing the addons as part of the Yamagi Quake II project, both we and most downstream projects like Linux distributions are forced to keep the main project and the addons seperated. And it makes merging code from and to the GPL2 licensed Yamagi Quake II hard.

With the Quake II Enhanced Edition id Software generously relicensed the unaltered addons source code under GPL2: https://github.com/id-Software/quake2-rerelease-dll This allows us to relicense our bugfixed versions of the addons. To do
that we need the okay from all past contributors.

You receive this message / heads up / tag because you have contributed at least one commit to the Yamagi Quake II Rogue project: https://github.com/yquake2/xatrix Please give us a short answer that you are okay with relicensing the project from the id Software SDK license to GPL2.

Listy of contributors on Github:

* [x] Adam Leskis - @lpmi-13
* [x] Andrey Nazarov - @skullernet
* [x] Angus Freudenberg - @afreuden
* [x] @BjossiAlfreds
* [x] @DanielGibson
* [x] David Carlier - @devnexen
* [x] Denis Pauk - @0lvin
* [x] @De-Seppe
* [ ] @Dremor8484
* [x] Jaime Moreira - @protocultor
* [x] Joshua Scoggins - @DrItanium
* [x] Mitchell Richters - @mjr4077au
* [x] @NeonKnightOA
* [x] Scott - @Pickle
* [x] @svdijk
* [x] Yamagi

**Comment by Yamagi** [comment]
* I give my okay.
* @DanielGibson gave me his okay.
* @BjossiAlfreds gave is okay in https://github.com/yquake2/rogue/pull/113
* @0lvin gave his okay in https://github.com/yquake2/rogue/pull/113
* @protocultor gave his okay in https://github.com/yquake2/rogue/pull/113

**Comment by Yamagi** [comment]
Of course you can give your okay here for both addons.

**Comment by lpmi-13** [comment]
Totally fine by me!

**Comment by devnexen** [comment]
> Of course you can give your okay here for both addons.

Yes sure :)

**Comment by DrItanium** [comment]
Yup, go for it

**Comment by skullernet** [comment]
I agree with relicensing (for both addons).

**Comment by mjr4077au** [comment]
Ok from me for any code I've submitted to any of the hosted projects here 🤜🤛

**Comment by NeonKnightOA** [comment]
I give my okay.

This isnvery good news for everybody.

**Comment by Yamagi** [comment]
Hi,

we are currently in the process of relicensing the Yamagi Quake II addon libraries from the proprietary id Software SDK license to GPL2. This was made possible by id Software, which has included a GPL2 licensed copy of the unaltered addons source code into the Quake II Enhanced Edition SDK. See https://github.com/id-Software/quake2-rerelease-dll for details.

Since you have contributed at least one commit to the Yamagi Quake II The Reconing (xatrix) and / or Ground Zero (rogue) subprojects we need you okay to continue with the relicensing. Please give us a short notice either here or by mail to yamagi@yamagi.org if you are okay with the relicensing.

Thank you!

@afreuden 
@Dremor8484 
@Pickle 
@svdijk

**Comment by svdijk** [comment]
Ok from me for any code I've submitted to this repo!

**Comment by Pickle** [comment]
You have my permission to re-license my contributions

**Comment by Yamagi** [comment]
@afreuden and @Dremor8484, please give us you okay to license Ground Zeot for Yamagi Quake II from the id Software SDK License to GPL2.

@afreuden has one commit,c18ba3bd91729e06a4cf80fb32ea158bc2bc3886 . It's a trivial change to the Makefile which translates to line 203 to 206 in the current git HEAD.

@Dremor8484 has several commits:
* c083b7c66cecbd0c4b273b6637904b58e8f4ce1b -> Mapfix for rmine1, submitted by @Dremor8484 and committed by me.
* 6de4a9ce77ff72bcf784f68dc93a20e268ddee5d -> The same code is in yquake2.
* e2ac13dae45858b284311a317376ce6d70cfe29e -> Addition to the previous change, the same code is in yquake2.
* 5d767c6b3082db11ca125a995b7a546de1d3b452 -> Trivial bugfix to the flechettes pickup code, exclusive to rogue.

**Comment by afreuden** [comment]
@Yamagi Nil issues from me, as above my one commit was trivial XD

**Comment by Yamagi** [comment]
@Dremor8484, we need your okay to relicense Ground Zero from the id Software SDK license to GPL2.

**Comment by Yamagi** [comment]
Ground Zero aka rogue is now GPL2 licensed.
