### ISSUE TITLE
[Request] Bring back the Disruptor/Disintegrator

### ISSUE THREAD

**Issue by drogga** [yquake2/rogue#17]
Entering "give disruptor" results in "Item cannot be given"

**Comment by NeonKnightOA** [comment]
I've made a pull-request with a cvar that enables/disables the weapon. If g_disruptor is 0, the weapon and its ammo shouldn't spawn; with other values.
Test this **but remember to back up rogue/game.so first**: https://www.dropbox.com/s/p8oif5cyxvvthwu/rogue-disruptortest.zip?dl=0

**Comment by drogga** [comment]
Thanks, problem is Dropbox says the link couldn't be found. Also I forgot to mention I'm on Windows, so I would need a .dll. Thanks for taking your time :)

**Comment by NeonKnightOA** [comment]
Oh, yeah, forgot about that, re-compiling.

**Comment by NeonKnightOA** [comment]
@drogga are you using 64-bit or 32-bit Quake II?

**Comment by drogga** [comment]
When g_disruptor is set to 1, will it also spawn in singleplayer, or do the spawn flags in the corresponding maps need to be edited accordingly?

**Comment by Yamagi** [comment]
I've just pushed a commit (based upon @NeonKnightOA idea) that adds the disruptor back. If `g_disruptor` is set to 0 (the default) it can be given, if set to 1 it's spawned in.
