### ISSUE TITLE
Resolve issues found by PVS

### ISSUE THREAD

**Issue by demoth** [yquake2/rogue#19]
Hi

I have run PVS against the code. Attaching the report.

https://docs.google.com/spreadsheets/d/1wHYBPlfs1c38zmmqEBVdXHng0glPy0CtYWKQncQZuYY/edit?usp=sharing

**Comment by Yamagi** [comment]
Most problems were addressed in pull request #33. Thank you again for the analysis!

**Comment by demoth** [comment]
I'm glad I was some help.
By the way right now I'm reviving the Jake2 project - quake2 Java port. Not
yet shining but planning to polish the code and add some features
eventually.

Best regards,
Daniil
