### ISSUE TITLE
[Suggestion] coop_baseq2 cvar for playing rogue co-op in non-rogue maps

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#29]
First let's see what the problem is. Open up rogue, set coop to 1 and open a baseq2 map of your choice, for example base1. You will see that something is not right - there are a lot more items laying around as well as visible spawnpoints. These are actually DM items.

The reason for this is that rogue decided to change how spawnflags are interpreted. They make use of the not-coop flag, and treat not-easy | not-medium | not-hard collectively as coop-only. These new rules break baseq2 maps whose flags have a different meaning than in rogue maps.

The simplest way around this would be to introduce a boolean cvar, for example called coop_baseq2, that will treat spawnflags the same way as baseq2 does, allowing co-op to be played in maps that are intended for baseq2.

If you are interested I can provide a pull request for this.

**Comment by Yamagi** [comment]
That sounds like a good addition. A pull request would be nice.
