### ISSUE TITLE
[Semi-original bug] Monsters don't always react to tesla zapping them

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#53]
To reproduce:
1. Go to map jail2
2. Execute "give all" and "notarget"
3. Throw a tesla in-between the two infantry/enforcer guys near the start of the level
4. When the tesla zaps both guys, you will observe that only one of them will actually get mad at the tesla and attack it

I call this semi-original because, while the bug is in the original rogue source code, it is actually not in the gamex86.dll that ships with the game (at least not with my CD copy). My guess is that rogue made this change after the game was packaged.

The reason for this can be found in M_ReactToDamage() in g_combat. Notice that the code that checks for tesla inflictor will only tell targ to target the tesla if it is a new tesla, which will only be true once, so the other guy doesn't react because new_tesla is false in the 2nd call.

I will provide a PR that takes care of this.

**Comment by Yamagi** [comment]
I've merged the pull request. Thank you.
