### ISSUE TITLE
[Original bug] Machinegun guards can freeze in place when ducking down

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#60]
Steps to reproduce (may require many attempts due to randomized ducking behavior):
1. Equip the hyperblaster
2. Get a machinegun guard angry at you
3. At the exact moment he is firing his machinegun, fire your hyperblaster at the top of his body to get him to duck down
4. If timed correctly and he decides to duck down, he will freeze in his ducking move, not even reacting to damage

This happens because AI_HOLD_FRAME leaks out of the guard's attack move into the ducking move, holding the first ducking frame forever since there is nothing in the frame's callback function to stop it.

There is a fail-safe against this inside M_MoveFrame() but a subtle difference in rogue's new guard ducking code manages to slip past that fail-safe. Notice that rogue sets .nextframe as well as .currentmove inside guard's ducking function, while baseq2 and xatrix only set .currentmove. This is an important detail because by setting .nextframe, M_MoveFrame() will think that this is not a new move, and thus set the current frame to nextframe and not clear AI_HOLD_FRAME.

I would say that AI_HOLD_FRAME should be cleared in this situation, since changing to a new frame strongly implies you don't want AI_HOLD_FRAME to stayset. In addition, setting .nextframe is completely unnecessary in this case and can be safely removed, causing AI_HOLD_FRAME to get cleared as it should.

While investigating this I also spotted another possible bug: .nextframe can linger around and leak into a future move. .nextframe is only reset to 0 if it gets used, if .nextframe is not within the current move, it will stay set all the way until the next time the compatible move is used, skipping the move straight to that frame. This can happen with interrupted moves, like if .nextframe is set and then you trigger a pain or ducking move before the next call to M_MoveFrame().

I will do a PR that fixes this problem. I will also likely do PRs that apply some of the added fail-safes into baseq2 and xatrix.

**Comment by Yamagi** [comment]
I wonder how do you manage to find these obscure bugs. And how much time was or is necessary to fix them. But, as always, thanks for the fix. :)

**Comment by BjossiAlfreds** [comment]
Since 2007 (on and off) I've been developing my own hobby mod where I add a whole bunch of cvars and commands that let players customize the gameplay. Change weapon damage/max ammo/projectile speed/accuracy/kick, scale/randomize monster stats (damage, health) give monsters random powerups/shields/armor, etc. etc. All these new features makes it easier for rare bugs to happen since they give you more power to orchestrate certain scenarios that would otherwise rarely/never happen. I ran into this specific bug when doing some work on defender spheres, it was a coincidence I was testing it in base2 on the machinegun guards, the sphere blaster made them duck and that is when it happened.

When I run into a bug I debug it and figure out exactly what is going on. Often it is bugs introduced by my code changes but for bugs that seem to be in the original game I load up the game with the original 1998 v3.20 dll and reproduce them there. If I manage to do that, like in this case where I managed to make the machinegun guard freeze within 5 minutes of loading base2 in the current rogue game.dll, I note it down and more recently forward to you.

I think it was 1-2 years ago that I discovered and fixed this one in my mod. But there are fairly recent ones, like the berserker idle move bug, that one I reported to you just days after I figured out what caused it. Though I had run into it a few times over the years, just never looked deeply into it until then.

**Comment by Yamagi** [comment]
I've just merged the PRs for xatrix and baseq2.

> When I run into a bug I debug it and figure out exactly what is going on. Often it is bugs introduced by my code changes but for bugs that seem to be in the original game I load up the game with the original 1998 v3.20 dll and reproduce them there. If I manage to do that, like in this case where I managed to make the machinegun guard freeze within 5 minutes of loading base2 in the current rogue game.dll, I note it down and more recently forward to you.

I just admire how much time and energy you spend fixing even the most obscure bug in the code. I have found and fixed quite a few bugs in baseq2 and both addons, but I never went that far. At some point I lacked the motivation for that. And these days I just don't have the time for it, anymore.

**Comment by BjossiAlfreds** [comment]
Comes from my passion for the game and for programming. In fact the Q2 code base was my very first programming experience, in the beginning I knew nothing, not even what a function was. Any time I see an oddity, no matter how small, it becomes a challenge in my brain that I absolutely must figure out and fix.
