### ISSUE TITLE
[Original bug] Disguise gets lost on level transitions

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#64]
I discovered this one just today.

For a bit of background: In rammo2, there is a machine you step into that briefly fills with water and then releases you again. The small space in the machine contains a trigger_disguise field that puts a disguise on you. While disguised, you will not be detected as an enemy by monsters unless you fire a gun or step through a trigger_disguise that is set to remove the disguise.

There is another trigger_disguise located in a level transition room in rammo1 that is supposed to wipe the disguise away when you return after being in rammo2. However, this doesn't quite work as originally intended because the FL_DISGUISED flag is not saved on level transitions, so it gets cleared when the entity structure is reset.

The fix is very simple - just add the FL_DISGUISED flag to savedFlags in player/client.c. I don't think this would negatively impact gameplay by making this part of the game easier, I didn't even know about this mechanic until very recently in fact. What are your thoughts?

**Comment by NeonKnightOA** [comment]
Not that it serves much on regular campaign considering that you need to blow up your cover in the next level, but on possible custom GZ campaigns which rely on disguises it may be a problem, indeed.

**Comment by NeonKnightOA** [comment]
I'll take care of this one.

**Comment by Yamagi** [comment]
I've merged the pull request. Thank you for having patients with me.
