### ISSUE TITLE
[Original bug] Turrets have no attack delay in melee range

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/rogue#65]
Steps to reproduce:
1. Open rammo1 in hard or nightmare and set notarget on
2. Teleport to -470 400 1370
3. Damage the blaster turret on the wall and stand right under it
4. The turret will shoot very very fast, 10 shots per second

I discovered this one the other day by accident. Basically, if the turret's enemy gets within melee range, the turret will rapid fire. You can rarely get close enough to a turret for this to happen during normal gameplay (and you typically don't want to get that close) but there are a few, like the one I explained above.

I found the problematic code in the turret's checkattack function. It seems to have been a simple oversight during copy/pasting. The no-delay thing isn't a problem for other monsters because their attack moves last several frames, while the turret's attack move is just 1 frame. I would say that the best fix is to remove the melee range exception entirely - making the turrets behave the same in melee range as they do from a distance.

**Comment by NeonKnightOA** [comment]
Taken care about.
