### ISSUE TITLE
ammo_disruptor and weapon_disintegrator not showing in Yamagi vs Retail

### ISSUE THREAD

**Issue by oGkspAz** [yquake2/rogue#69]
I was editing an fgd for Ground Zero and thought I was making a mistake with the items when I test map but I found it shows up in retail.

![Quake II v3 24 - rdm1 Disruptor](https://user-images.githubusercontent.com/13630539/79564278-a2126200-80ae-11ea-8ad8-d3f40a5cd5b2.jpg)
![Quake II Yamagi v7 43 - rdm1 Disruptor](https://user-images.githubusercontent.com/13630539/79564284-a63e7f80-80ae-11ea-85c0-4aa9cf827485.jpg)

**Comment by BjossiAlfreds** [comment]
Try set g_disruptor to 1 if you haven't already, that enables YQ2's Disruptor support, or at least it should.

On a side note, the Disruptor is actually completely absent from the original version of GroundZero, where most of its code doesn't even exist in the gamex86. Judging by the console output you are using an unofficial version (see the 3.24 at the bottom right) as a reference, which may have added the Disruptor as a bonus feature.

**Comment by oGkspAz** [comment]
Ah, I saw on the Wiki the weapon was cut but still found it ingame. I didn't realise it was one of the features v3.24 added.
PS. g_disruptor works.
