### ISSUE TITLE
medic_checkattack in m_medic. needs self->enemy sanity check before self->enemy->client

### ISSUE THREAD

**Issue by maraakate** [yquake2/rogue#7]
Got a crash on my coop server in medic_checkattack.  There is 

``if (self->enemy->client &&
!visible(self, self->enemy) && (self->monsterinfo.monster_slots > 2))``

There needs to be a self->enemy check at the beginning of this statement.  See https://bitbucket.org/neozeed/q2dos/commits/4218f8ba33bee16f7fafdf4eb40cc8ef565c7536 for additional info.

**Comment by Yamagi** [comment]
And it's finally merged. Thank you. :)
