### ISSUE TITLE
Enemies attack through walls

### ISSUE THREAD

**Issue by Player701** [yquake2/rogue#9]
Hey there. During my playthrough this issue manifested in Ground Zero exlusively, so I'm reporting it here. It appears that some enemies - particularly Parasites - are able to attack the player through walls; this mostly happened to me when I tried to hide from them around corners. I'm not sure if this is an issue with this particular type of enemy, though. I swear I saw a gunner lob grenades at me through a wall once...

This bug can be easily reproduced on the "Munitions Plant" level (rammo1) on hard difficulty; there is a Parasite in the starting area, so conveniently placed that the probability of the bug happening is very high. But I also made a save to make testing even simpler. Just load it and you should see it. (If you don't, try loading it a few more times, or just load the map from scratch and try it yourself)

Links: [screenshot](https://mega.nz/#!Xol1BRgI!DwEB_J_uLrecU43WjDI8ar1cHZ7sySMgPtqcAKZ_h-8), [save file](https://mega.nz/#!Gw1kUYLB!oCDZLQdsIxXi0KZprtp9vuYT1z36jZXWXC3SO-hmmgc)

**Comment by Yamagi** [comment]
We just pushed a commit. Sorry for the long delay.

**Comment by Player701** [comment]
Nevermind, thank you! Not sure if I will start another playthrough soon, though, but if I do, I will certainly be happy that the bug is gone now.

**Comment by Yamagi** [comment]
A new set of Windows binaries (let's call it 7.41-RC1) with this fix included can be found here: https://deponie.yamagi.org/quake2/misc/quake2-298cb05-20190513.zip
