### ISSUE TITLE
[bug] 1 monster berserker is stuck in rmine1, fixed .ent file available here

### ISSUE THREAD

**Issue by Dremor8484** [yquake2/rogue#90]
the monster berserker spawns ONLY after the player completed all objectives, and is returning to the first map to exit the unit 1
the monster is at the top of a rock ramp, that rock ramp is next to the exit of the level to Thaelite Mines (RLAVA1)

{
"origin" "968 544 744" //stuck monster at "968 544 720" (it spawns after Tectonic Stabilizer objectives are completed)
"angle" "0"
"spawnflags" "3"
"targetname" "t350"
"classname" "monster_berserk"
}

here is a link to the fixed .ent file
https://drive.google.com/drive/folders/1DuJ13cMP-G_l-tW4_DF-m9k_0BgKiflv?usp=sharing

**Comment by Yamagi** [comment]
Good find! I've commited the entity file.
